### ISSUE TITLE
destination of public folder

### ISSUE THREAD

**Issue by t-mon** [guh/guh-webserver#2]
I am planing to install the guh-webserver to `/usr/bin`, but the public folder with the guh-webinterface should be in `/usr/share/guh-webinterface`.

Is it possible to load the webinterface from that location? Or is it maby possible to check if there is a public folder next to the executable, if so, publish that folder, if not, publish the folder `/usr/share/guh-webinterface/public` ?

**Comment by mzanetti** [comment]
Ideally the webserver would have a config file to tell it where to load the content from...

**Comment by wukerplank** [comment]
Ok, shouldn't be a problem!

**Comment by wukerplank** [comment]
Implemented with the latest commits to guh-webserver and guh-libgo.
