### ISSUE TITLE
Attribute "inputType" missing in paramTypes

### ISSUE THREAD

**Issue by rhythm-section** [guh/guh-webserver#8]
Inside all "paramTypes" should be an attribute called "inputType". It is used to distinguish between different text input fields. For example the inputType "InputTypePassword" is used to know that this paramType should be shown as <input type="password" /> and not as <input type="text" />. As far as I know the "inputType" is already inside "actionTypes" of a "DeviceClass". But the attribute is missing inside "paramTypes" of a "DeviceClass". Maybe the attribute is also missing inside "discoveryParamTypes" and "eventTypes". 

For example the paramTypes of the DeviceClass "Google mail" should look like this (from guh-cli):
"paramTypes": [
  {
    "inputType": "InputTypeMail",
    "name": "user",
    "type": "QString"
  },
  {
    "inputType": "InputTypePassword",
    "name": "password",
    "type": "QString"
   },
   {
     "inputType": "InputTypeMail",
     "name": "recipient",
     "type": "QString"
  }
]

The server response is the same except that alls "inputType" attributes are missing.

**Comment by wukerplank** [comment]
This issue should be fixed with the latest commit to guh-libgo.
